language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t dorcaschan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dorcaschan/docker-react npm run test -- --coverage
